# Generated by Django 2.2.5 on 2019-10-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('atvcode', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('exp', models.DateTimeField()),
                ('point', models.FloatField()),
                ('used', models.BooleanField()),
                ('code', models.TextField(primary_key=True, serialize=False)),
                ('atvcode', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='api.Activity')),
            ],
        ),
    ]
