# Generated by Django 2.2.5 on 2019-10-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
