# Generated by Django 2.2.5 on 2019-10-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='place',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
