# Generated by Django 2.2.6 on 2019-10-15 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191015_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='used_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='code',
            name='used_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
