# Generated by Django 2.2.6 on 2019-10-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191015_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='used_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
