# Generated by Django 2.2.6 on 2019-10-15 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191015_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='atvname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Activity'),
        ),
    ]
